name: sharding-repl-cache

services:
  pymongo_api:
    container_name: pymongo_api
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos_router
    ports:
      - 8080:8080
    networks:
      - app-network
    environment:
      MONGODB_URL: "mongodb://mongos_router:27024"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis_1:6379"

  
  redis_1:
    container_name: redis_1
    image: redis:latest
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    networks:
      - app-network
    volumes:
      - redis_1_data:/data

  config_server_replica1:
    image: mongo:latest
    container_name: config_server_replica1
    restart: always
    ports:
      - 27015:27015
    networks:
      - app-network
    volumes:
      - config-replica1-data:/data/db
    command:
      [
        "mongod",
        "--configsvr",
        "--replSet",
        "config_server_rs",
        "--bind_ip_all",
        "--port",
        "27015"
      ] 
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  config_server_replica2:
    image: mongo:latest
    container_name: config_server_replica2
    restart: always
    ports:
      - 27016:27016
    networks:
      - app-network
    volumes:
      - config-replica2-data:/data/db
    command:
      [
        "mongod",
        "--configsvr",
        "--replSet",
        "config_server_rs",
        "--bind_ip_all",
        "--port",
        "27016"
      ] 
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  config_server_replica3:
    image: mongo:latest
    container_name: config_server_replica3
    restart: always
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - config-replica3-data:/data/db
    command:
      [
        "mongod",
        "--configsvr",
        "--replSet",
        "config_server_rs",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1_replica1:
    image: mongo:latest
    container_name: shard1_replica1
    restart: always
    ports:
      - 27018:27018
    networks:
      - app-network
    volumes:
      - shard1-replica1-data:/data/db
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet",
        "shard1_rs",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1_replica2:
    image: mongo:latest
    container_name: shard1_replica2
    restart: always
    ports:
      - 27019:27019
    networks:
      - app-network
    volumes:
      - shard1-replica2-data:/data/db
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet",
        "shard1_rs",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1_replica3:
    image: mongo:latest
    container_name: shard1_replica3
    restart: always
    ports:
      - 27020:27020
    networks:
      - app-network
    volumes:
      - shard1-replica3-data:/data/db
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet",
        "shard1_rs",
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2_replica1:
    image: mongo:latest
    container_name: shard2_replica1
    restart: always
    ports:
      - 27021:27021
    networks:
      - app-network
    volumes:
      - shard2-replica1-data:/data/db
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet",
        "shard2_rs", 
        "--bind_ip_all",
        "--port",
        "27021"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2_replica2:
    image: mongo:latest
    container_name: shard2_replica2
    restart: always
    ports:
      - 27022:27022
    networks:
      - app-network
    volumes:
      - shard2-replica2-data:/data/db
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet",
        "shard2_rs", 
        "--bind_ip_all",
        "--port",
        "27022"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
  
  shard2_replica3:
    image: mongo:latest
    container_name: shard2_replica3
    restart: always
    ports:
      - 27023:27023
    networks:
      - app-network
    volumes:
      - shard2-replica3-data:/data/db
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet",
        "shard2_rs", 
        "--bind_ip_all",
        "--port",
        "27023"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - 27024:27024
    networks:
      - app-network
    command:
      [
        "mongos", 
        "--configdb", 
        "config_server_rs/config_server_replica1:27015,config_server_replica2:27016,config_server_replica3:27017",
        "--bind_ip_all",
        "--port",
        "27024"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

volumes:
  config-replica1-data:
  config-replica2-data:
  config-replica3-data:
  shard1-replica1-data:
  shard1-replica2-data:
  shard1-replica3-data:
  shard2-replica1-data:
  shard2-replica2-data:
  shard2-replica3-data:
  redis_1_data: